#ifndef GRAPHICS_CONSTANTS_H
#define GRAPHICS_CONSTANTS_H


// Window constants
#define WINDOW_WIDTH 1000
#define WINDOW_HEIGHT 750

#define WINDOW_CENTER_X WINDOW_WIDTH/2
#define WINDOW_CENTER_Y WINDOW_HEIGHT/2


// Device drawing constants
#define DEVICE_IMAGE_WIDTH 69
#define DEVICE_IMAGE_HEIGHT 69

// Arrow drawing constants
#define ARROW_IMAGE_WIDTH 125
#define ARROW_IMAGE_HEIGHT 40



#define INITIAL_INTERNAL_DEVICE_X 50
#define INITIAL_INTERNAL_DEVICE_Y 50

#define INITIAL_EXTERNAL_DEVICE_X WINDOW_CENTER_X + INITIAL_INTERNAL_DEVICE_X
#define INITIAL_EXTERNAL_DEVICE_Y INITIAL_INTERNAL_DEVICE_Y


#define DEVICE_SPACING_X DEVICE_IMAGE_WIDTH * 2
#define DEVICE_SPACING_Y DEVICE_IMAGE_HEIGHT * 1.75


#define INTERNAL_DEVICE_MAXIMUM_X WINDOW_CENTER_X - DEVICE_SPACING_X
#define INTERNAL_DEVICE_MAXIMUM_Y WINDOW_HEIGHT - DEVICE_SPACING_Y

#define EXTERNAL_DEVICE_MAXIMUM_X WINDOW_WIDTH - DEVICE_SPACING_X
#define EXTERNAL_DEVICE_MAXIMUM_Y WINDOW_HEIGHT - DEVICE_SPACING_Y


#endif
